### ISSUE TITLE
Support for Spark Streaming

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-spark-connector#1]
Hi does this support Spark Streaming?  If so is there any example code on integrating with Spark Streaming?

Thanks,

**Comment by mvollmary** [comment]
Currently not. But our Spark Connector is in an very early stage of development and we're discussing what Spark features we want to support. Spark Streaming could be implemented within the next updates.

We are trying to find out what Spark developers really need. It would be great if you try our Spark Connector out and give us feedback on what you think.

**Comment by hpilosyan** [comment]
Hi, is this feature on your radar?

**Comment by mvollmary** [comment]
It is part of a very long list of TODOs for 2018. At the current time I don't know when we have time for it.

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).
If this issue is still relevant please reopen it in the new connector's project.
