### ISSUE TITLE
Partition-individual filtering and other improvements

### ISSUE THREAD

**Issue by zawlazaw** [arangodb/arangodb-spark-connector#14]
I evaluate choosing ArangoDb + Spark for advanced analytics, and I would like to contribute additional functionality that goes far beyond my trivial PR #12 :).

I am particulary interested in more advanced flexibility in selecting and partitioning the documents that are transferred from an ArangoDb collection to a Spark RDD.

As a reference approach, let us look at the three phases of MongoDb's spark-connector:

- Phase 1) (optional) run an arbitrary aggregation-pipeline (filtering, projection, and all other kinds of fancy processing) on a collection
- Phase 2) handle the result, or the whole collection, by a partitioner that prepares one db-query per partition (e.g., partition by estimated partition size, or by same document count per partition, etc.)
- Phase 3) transfer the documents to Spark by running all these db-queries via one cursor per partition

The current implementation of arangodb-spark-connector supports the following two features:
- (F1) global AQL filters can be defined that are applied to all partitions in order to breakdown the overall amount of data passed to the RDD.
- (F2) there are two partitioner strategies: one that creates a single partition for all data, and one that creates one partition per shard. As a consequence, in a single-server-setup we cannot create an RDD with more than one partition, although it would likely increase performance if we could split the data into multiple partitions. Similar for a cluster setup: it can be beneficial (because of many CPU cores) to create more partitions that shards. For example, assume we have 5 shards, but we want to split them into 40 partitions (8 partitions per shard).

The main new features that I would like to achieve are:
- (F3) define an individual filter per partition via convenient helper methods (e.g., equidistant value ranges). This allows, for example, to create one partition per month on an indexed timestamp-field, independent on the number of shards.
- (F4) in addition to (F3), make it possible to additionally subdivide such range-filters by shards. For example, we query 6 value-ranges of data, and further want to restrict each partition to contain data of only one of our 5 shards (probably because of data locality reasons). This gives 30 partitions (1 per value-range per shard).
- (F5) optionally, avoid to create empty partitions (e.g., run a LIMIT 1 check query before actually creating the partition, as it is similarly supported by MongoDb)
- (F6) apply a global projection (the same for all partitions) to each transferred document in order to select only certain fields of the document rather than transferring the full document 

Some additional nice-to-haves are:
- (F7) represent the existing partitioners (single-partition and one-partition-per-shard) as special cases of (F4).
- (F8) provide a partitioner that uses some heuristic to partition all data into partitions of roughly same byte-size (requires access to statistics on the average-document-size in the collection)
- (F9) provide a partitioner that uses some heuristic to partition all data into partitions of roughly the same number of documents
- (F10) ensure that a partition that consumes all its data from just a single shard lies on the same physical machine as the shard (if ArangoDb runs next to Spark Workers on the same hardware).

Note that some data inconsistency is acceptable: the partitions do not need to refer to a globally consistent snapshot (e.g., some later fetched partitions may contain later added documents. Or a partition was checked to be empty and is thus ignored, although immediately afterwards a document is added to it, even before the first partition is actually fetched).

Let me end this long text with two questions:
- 1.) Do you have any comments, concerns, suggestions on the above features?
- 2.) Since this github project currently seems to be not that strongly active, how are priorities and resources currently assigned at ArangoDb for improving arangodb-spark-connector? I already implemented large parts of the above (F3)-(F6), which would result in a bigger PR. Is it realistic that such a PR would be reviewed here and finally merged? Or should I for now better focus on my own fork of the repo?

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).
If this issue is still relevant please reopen it in the new connector's project.
