### ISSUE TITLE
NullPointerException saving Dataframe

### ISSUE THREAD

**Issue by Appuv1** [arangodb/arangodb-spark-connector#15]
There is a null pointer exception when trying to save a dataframe to a collection.
The error is coming when null is coming at an array type.
This is where we feel the error is
 line 77 of VPackUtils.scala,
row.getSeq(i).foreach { value => addValue(null, value, builder) }
which will produce this exception if row.getSeq(i) is null.

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/arangodb-spark-connector/commit/de27b4f33cf020ff4dee53f2f9988e62c8194e47

**Comment by Appuv1** [comment]
Thanks:)
