### ISSUE TITLE
saving to ArangoDb using Dataset

### ISSUE THREAD

**Issue by tanroopdhillon** [arangodb/arangodb-spark-connector#2]
I tried the follwing:
ArangoSpark.save(**finalCust**, "CollectionName");

**here finalCust is of the type Dataset<Row>.**

But I got the following error:
**Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.Dataset.toDF()Lorg/apache/spark/sql/DataFrame;
	at com.arangodb.spark.ArangoSpark$.save(ArangoSpark.scala:87)
	at com.arangodb.spark.ArangoSpark.save(ArangoSpark.scala)
	at com.myntra.ats.application.SparkApplication.main(SparkApplication.java:133)**

My dependecies are:
compile("org.apache.spark:spark-core_2.11:2.1.1")
    compile("org.apache.spark:spark-sql_2.11:2.1.1")
    compile("org.apache.spark:spark-streaming_2.11:2.1.1")
    compile("com.arangodb:arangodb-spark-connector:1.0.0")

Please help :)

**Comment by mvollmary** [comment]
Hi, 
thanks for reporting. This was a bug in the connector which I fixed already. I am releasing a new version (1.0.1) right now. It should be available on maven central repo within the next hours.

**Comment by sleto-it** [comment]
Hi @tanroopdhillon ,

Just wondering - have you had a chance to check release 1.0.1? has your problem been solved?
Please note that we just released version 1.0.2

Let us know if we can consider this ticket resolved

Many thanks,

**Comment by mvollmary** [comment]
I will close this issue, feel free to open it again if your problem is still not solved
