### ISSUE TITLE
can we add UPSERT option in write options?

### ISSUE THREAD

**Issue by wangkailut** [arangodb/arangodb-spark-connector#22]

**Comment by rashtao** [comment]
With the upcoming `ArangoDB 3.7` we can support `insert-update` and `insert-replace`: https://github.com/arangodb/docs/blob/562b88a50d62a1ea0a16203cc2d755c6068509c1/3.7/release-notes-api-changes37.md#endpoints-augmented
I will implement support for such features once `ArangoDB 3.7` will be released.
In the meantime you can explicitly set the `WriteOptions.method` to `INSERT`, `UPDATE` or `REPLACE` (https://github.com/arangodb/arangodb-spark-connector/blob/master/src/main/scala/com/arangodb/spark/WriteOptions.scala#L94-L119).

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).
If this issue is still relevant please reopen it in the new connector's project.
