### ISSUE TITLE
arangodb.hosts should be changed to spark.arangodb.hosts #228

### ISSUE THREAD

**Issue by lizhizhou** [arangodb/arangodb-spark-connector#3]
The spark property should have a prefix of spark else the property cannot be added in spark-shell and spark-submit by --conf option

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).
If this issue is still relevant please reopen it in the new connector's project.
