### ISSUE TITLE
Support for GraphX

### ISSUE THREAD

**Issue by AStoopidFakeAccount** [arangodb/arangodb-spark-connector#9]
Hi,

I've been using a bit the ArangoDB spark connector lately,

I know this is the early stage for this connector but this should be kind of mandatory : make the connector natively support the GraphX library.

With Spark GraphX Pregel implementation you can run customised Pregel algorithms which I think can interest a lot of people, otherwise they probably wouldn't bother to use the connector since the "classic" Pregel algorithms are already available directly from ArangoDB.

Besides ArangoDB being a Graph Database, it feels only natural to support the library to manipulate Graph in Spark.

Thanks,

Best regards.

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).
If this issue is still relevant please reopen it in the new connector's project.
